services:
  - type: web
    name: projectcreator-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    pythonVersion: 3.10
